---
- name: Update apt
  apt:
    upgrade: dist

- name: Install/Upgrade apt packages
  apt:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('latest') }}"
  with_items: "{{ apt_packages }}"
  when: apt_packages
